[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "auto"
maxUploadSize = 200

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
font = "sans serif"
